const nodemailer = require('nodemailer');

// Initialize Nodemailer Gmail SMTP Transporter
const createTransporter = () => {
    const user = process.env.EMAIL_USER;
    const pass = process.env.EMAIL_APP_PASSWORD;

    if (!user || !pass || pass.includes('xxxx')) {
        console.warn("[EmailService] Gmail SMTP credentials not fully configured in environment variables.");
    }

    return nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 465,
        secure: true, // SSL
        auth: {
            user: user,
            pass: pass
        }
    });
};

/**
 * Clean & sanitize string inputs to prevent HTML/header injection
 */
function sanitizeString(str) {
    if (!str || typeof str !== 'string') return '';
    return str.replace(/[\r\n\t]/g, ' ').replace(/[<>]/g, '').trim();
}

/**
 * Send an emergency SOS email to a single recipient
 */
async function sendEmergencyEmail({
    recipientEmail,
    recipientName = 'Emergency Contact',
    userName = '',
    latitude,
    longitude,
    accuracy = 10,
    googleMapsUrl,
    date = new Date().toLocaleDateString(),
    time = new Date().toLocaleTimeString(),
    battery = 'N/A',
    deviceInfo = '',
    isTest = false
}) {
    const cleanRecipientName = sanitizeString(recipientName) || 'Emergency Contact';
    const mapsUrl = googleMapsUrl || `https://www.google.com/maps?q=${latitude},${longitude}`;
    
    // Subject Line
    const subject = isTest ? '⚠️ NAZAR Emergency System Test' : '🚨 Emergency Assistance Alert - NAZAR';

    // Plain Text Version
    const textBody = isTest 
        ? `This is a test email generated by the NAZAR Emergency System.\n\nNo assistance is required.\n\nCurrent Location:\n${mapsUrl}\n\nLatitude:\n${latitude}\n\nLongitude:\n${longitude}\n\nAccuracy:\n${accuracy} meters\n\nDate:\n${date}\n\nTime:\n${time}\n\nBattery:\n${battery}\n\nGenerated automatically by NAZAR Accessibility Assistant.`
        : `Emergency Alert\n\nEmergency assistance has been requested through the NAZAR application.\n\nCurrent Location:\n${mapsUrl}\n\nLatitude:\n${latitude}\n\nLongitude:\n${longitude}\n\nAccuracy:\n${accuracy} meters\n\nDate:\n${date}\n\nTime:\n${time}\n\nBattery:\n${battery}\n\nPlease check on the user or proceed to the shared location.\n\nGenerated automatically by NAZAR Accessibility Assistant.`;

    // Responsive HTML Version
    const htmlBody = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${subject}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #0f172a; font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #f8fafc;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #0f172a; padding: 20px 10px;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; background-color: #1e293b; border-radius: 16px; overflow: hidden; border: 1px solid #334155; box-shadow: 0 10px 30px rgba(0,0,0,0.5);">
          
          <!-- Emergency Header Banner -->
          <tr>
            <td style="background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%); padding: 24px; text-align: center;">
              <h1 style="color: #ffffff; margin: 0; font-size: 22px; font-weight: 800; letter-spacing: 0.5px; text-transform: uppercase;">
                ${isTest ? '⚠️ NAZAR EMERGENCY TEST' : '🚨 EMERGENCY ALERT'}
              </h1>
              <p style="color: #fef2f2; margin: 6px 0 0 0; font-size: 14px; font-weight: 500;">
                ${isTest ? 'No assistance is required.' : 'Emergency assistance has been requested through the NAZAR application.'}
              </p>
            </td>
          </tr>
          
          <!-- Content Body -->
          <tr>
            <td style="padding: 24px;">
              <p style="font-size: 16px; line-height: 1.5; color: #cbd5e1; margin-top: 0;">
                Dear <strong>${cleanRecipientName}</strong>,
              </p>
              <p style="font-size: 15px; line-height: 1.6; color: #cbd5e1;">
                ${isTest 
                  ? 'This is a test message generated to verify NAZAR Emergency SOS email settings.'
                  : 'An urgent emergency assistance signal was triggered via the NAZAR Accessibility Assistant.'}
              </p>

              <!-- Map Action Button -->
              <table width="100%" cellpadding="0" cellspacing="0" style="margin: 24px 0 12px 0;">
                <tr>
                  <td align="center">
                    <a href="${mapsUrl}" target="_blank" style="display: inline-block; background-color: #ef4444; color: #ffffff; font-size: 15px; font-weight: 700; text-decoration: none; padding: 14px 24px; border-radius: 10px; box-shadow: 0 4px 14px rgba(239, 68, 68, 0.4);">
                      📍 Open Live Location on Google Maps
                    </a>
                  </td>
                </tr>
              </table>

              <!-- Plain Text Direct URL (Fallback for blocked buttons) -->
              <p style="font-size: 12px; color: #94a3b8; word-break: break-all; margin: 0 0 24px 0; text-align: center;">
                Direct Google Maps URL:<br>
                <a href="${mapsUrl}" target="_blank" style="color: #60a5fa; text-decoration: underline;">${mapsUrl}</a>
              </p>

              <!-- Details Table -->
              <table width="100%" cellpadding="10" cellspacing="0" style="background-color: #0f172a; border-radius: 10px; border: 1px solid #334155; margin-bottom: 20px;">
                <tr>
                  <td style="color: #94a3b8; font-size: 13px; border-bottom: 1px solid #334155; font-weight: 600;">Latitude</td>
                  <td style="color: #f8fafc; font-size: 14px; border-bottom: 1px solid #334155; font-family: monospace;">${latitude}</td>
                </tr>
                <tr>
                  <td style="color: #94a3b8; font-size: 13px; border-bottom: 1px solid #334155; font-weight: 600;">Longitude</td>
                  <td style="color: #f8fafc; font-size: 14px; border-bottom: 1px solid #334155; font-family: monospace;">${longitude}</td>
                </tr>
                <tr>
                  <td style="color: #94a3b8; font-size: 13px; border-bottom: 1px solid #334155; font-weight: 600;">GPS Accuracy</td>
                  <td style="color: #f8fafc; font-size: 14px; border-bottom: 1px solid #334155;">~${accuracy} meters</td>
                </tr>
                <tr>
                  <td style="color: #94a3b8; font-size: 13px; border-bottom: 1px solid #334155; font-weight: 600;">Date & Time</td>
                  <td style="color: #f8fafc; font-size: 14px; border-bottom: 1px solid #334155;">${date} at ${time}</td>
                </tr>
                <tr>
                  <td style="color: #94a3b8; font-size: 13px; font-weight: 600;">Battery Level</td>
                  <td style="color: #f8fafc; font-size: 14px;">${battery}</td>
                </tr>
              </table>

              <p style="font-size: 13px; color: #94a3b8; margin-bottom: 0;">
                Please contact ${cleanUserName} immediately or proceed to the shared location coordinates above.
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background-color: #0f172a; padding: 16px 24px; text-align: center; border-top: 1px solid #334155;">
              <p style="margin: 0; font-size: 12px; color: #64748b;">
                Generated automatically by <strong>NAZAR Accessibility Assistant</strong>
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

    const transporter = createTransporter();
    const mailOptions = {
        from: `"NAZAR Emergency Assistant" <${process.env.EMAIL_USER}>`,
        to: recipientEmail,
        subject: subject,
        text: textBody,
        html: htmlBody
    };

    return await transporter.sendMail(mailOptions);
}

/**
 * Send an "I'm Safe" follow-up email to a recipient
 */
async function sendSafeEmail({
    recipientEmail,
    recipientName = 'Emergency Contact',
    userName = '',
    date = new Date().toLocaleDateString(),
    time = new Date().toLocaleTimeString()
}) {
    const cleanRecipientName = sanitizeString(recipientName) || 'Emergency Contact';
    const subject = '✅ Update from NAZAR: Emergency Assistance Cleared';

    const textBody = `Update from NAZAR\n\nDear ${cleanRecipientName},\n\nThe user has indicated that they are now safe. Emergency assistance is no longer active.\n\nNo further emergency action is currently required.\n\nTime of Update:\n${date} at ${time}\n\nGenerated automatically by NAZAR Accessibility Assistant.`;

    const htmlBody = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${subject}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #0f172a; font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #f8fafc;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #0f172a; padding: 20px 10px;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; background-color: #1e293b; border-radius: 16px; overflow: hidden; border: 1px solid #334155; box-shadow: 0 10px 30px rgba(0,0,0,0.5);">
          <tr>
            <td style="background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%); padding: 24px; text-align: center;">
              <h1 style="color: #ffffff; margin: 0; font-size: 22px; font-weight: 800; letter-spacing: 0.5px;">
                ✅ EMERGENCY ASSISTANCE CLEARED
              </h1>
              <p style="color: #f0fdf4; margin: 6px 0 0 0; font-size: 14px; font-weight: 500;">
                No further emergency action required.
              </p>
            </td>
          </tr>
          <tr>
            <td style="padding: 24px;">
              <p style="font-size: 16px; line-height: 1.5; color: #cbd5e1; margin-top: 0;">
                Dear <strong>${cleanRecipientName}</strong>,
              </p>
              <p style="font-size: 15px; line-height: 1.6; color: #cbd5e1;">
                Emergency assistance has been marked as <strong>SAFE / CLEARED</strong> in the NAZAR application.
              </p>
              <p style="font-size: 14px; color: #94a3b8; background: #0f172a; padding: 12px 16px; border-radius: 8px; border: 1px solid #334155;">
                <strong>Time of Update:</strong> ${date} at ${time}
              </p>
            </td>
          </tr>
          <tr>
            <td style="background-color: #0f172a; padding: 16px 24px; text-align: center; border-top: 1px solid #334155;">
              <p style="margin: 0; font-size: 12px; color: #64748b;">
                Generated automatically by <strong>NAZAR Accessibility Assistant</strong>
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

    const transporter = createTransporter();
    return await transporter.sendMail({
        from: `"NAZAR Emergency Assistant" <${process.env.EMAIL_USER}>`,
        to: recipientEmail,
        subject: subject,
        text: textBody,
        html: htmlBody
    });
}

const { maskSecret } = require('../config');

/**
 * Verify SMTP connection on server startup
 */
async function verifyTransporterConnection() {
    try {
        const transporter = createTransporter();
        await transporter.verify();
        console.log(`[EMAIL SERVICE] Gmail SMTP connected & ready (${maskSecret(process.env.EMAIL_USER)})`);
        return true;
    } catch (err) {
        console.error("[EMAIL SERVICE] Gmail SMTP connection failed:", err.message);
        return false;
    }
}

module.exports = {
    sendEmergencyEmail,
    sendSafeEmail,
    verifyTransporterConnection
};
