const defaultCountryCode = process.env.OPENWA_DEFAULT_COUNTRY_CODE || '91';

/**
 * Validates and formats a phone number into a WhatsApp JID (@c.us) format.
 * @param {string} phone - The raw phone number input.
 * @returns {string|null} The formatted JID, or null if invalid.
 */
function formatPhoneNumber(phone) {
    if (!phone || typeof phone !== 'string') return null;

    // Remove non-numeric characters
    let cleaned = phone.replace(/[^0-9]/g, '');

    if (!cleaned) return null;

    // Handle exactly 10 digits by prepending the default country code
    if (cleaned.length === 10) {
        cleaned = defaultCountryCode + cleaned;
    }

    // A valid JID must have a country code + number.
    // Minimum digits for a mobile number globally is around 8-15 digits.
    if (cleaned.length < 8 || cleaned.length > 15) {
        return null;
    }

    return `${cleaned}@c.us`;
}

/**
 * Generates the standardized Emergency SOS alert text.
 * @param {number|string} lat - Latitude
 * @param {number|string} lng - Longitude
 * @param {number|string} accuracy - Accuracy in meters
 * @param {number} [timestamp] - Unix timestamp (seconds or ms) or Date object
 * @returns {string} The formatted message body.
 */
function formatRichSosMessage(lat, lng, accuracy, timestamp) {
    let timeStr = '';
    try {
        const dateObj = timestamp 
            ? (typeof timestamp === 'number' 
                ? (timestamp > 1000000000000 ? new Date(timestamp) : new Date(timestamp * 1000))
                : new Date(timestamp))
            : new Date();
        timeStr = dateObj.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    } catch (e) {
        timeStr = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    }

    const cleanAccuracy = accuracy ? Math.round(parseFloat(accuracy)) : 10;

    return `🚨 NAZAR Emergency Alert

The user has activated the Emergency SOS feature.

Current Location
https://www.google.com/maps?q=${lat},${lng}

Coordinates
Latitude: ${lat}
Longitude: ${lng}

Accuracy: ${cleanAccuracy} meters

Time: ${timeStr}

Generated by NAZAR Accessibility Assistant.

Please contact the user immediately.`;
}

module.exports = {
    formatPhoneNumber,
    formatRichSosMessage
};
